import {
  DashboardSummaryResponse,
  TransactionListItem,
  TransactionDetailResponse,
  RecoveryActionItem,
  AuditLogItem,
  AgentsOverviewResponse,
  EvaluationMetricsResponse,
} from "@/types/api";

export const MOCK_DASHBOARD: DashboardSummaryResponse = {
  metrics: {
    revenue_at_risk: 284210,
    recovered_revenue: 182450,
    recovery_rate: 64.2,
    active_actions_count: 38,
    total_transactions_analyzed: 10420,
    pending_human_approvals: 6,
    anomaly_detected: true,
    anomaly_message: "UPI failure rate spike detected in HDFC/SBI gateway (+4.8x normal baseline). Autonomous payment link fallback active.",
  },
  leakage_breakdown: [
    { category: "Payment Failures", amount: 72000, percentage: 37.7, color: "#ef4444" },
    { category: "Checkout Abandonment", amount: 48000, percentage: 25.1, color: "#f59e0b" },
    { category: "Invoices & Subscriptions", amount: 40000, percentage: 20.9, color: "#6366f1" },
    { category: "Bank Degradation", amount: 31000, percentage: 16.3, color: "#8b5cf6" },
  ],
  trend: [
    { date: "Mon", revenue_at_risk: 42000, revenue_recovered: 28500, recovery_rate: 67.8 },
    { date: "Tue", revenue_at_risk: 39000, revenue_recovered: 24100, recovery_rate: 61.7 },
    { date: "Wed", revenue_at_risk: 51000, revenue_recovered: 33400, recovery_rate: 65.4 },
    { date: "Thu", revenue_at_risk: 46000, revenue_recovered: 29800, recovery_rate: 64.7 },
    { date: "Fri", revenue_at_risk: 68000, revenue_recovered: 41200, recovery_rate: 60.5 },
    { date: "Sat", revenue_at_risk: 55000, revenue_recovered: 36500, recovery_rate: 66.3 },
    { date: "Sun", revenue_at_risk: 48000, revenue_recovered: 32100, recovery_rate: 66.8 },
  ],
  recent_queue: [
    {
      transaction_id: "txn_4999_upi",
      customer_name: "Aditya Verma",
      customer_email: "aditya.verma@example.com",
      amount: 4999,
      currency: "INR",
      payment_method: "upi",
      failure_reason: "upi_timeout",
      detected_issue: "UPI PSP timeout / payment degradation",
      ai_recommendation: "payment_link",
      confidence: 0.91,
      recovery_probability: 0.87,
      expected_recovery: 4349.13,
      policy_decision: "APPROVED",
      status: "failed",
      created_at: "Just now",
    },
    {
      transaction_id: "txn_12450_card",
      customer_name: "Priya Sharma",
      customer_email: "priya.s@techcorp.in",
      amount: 12450,
      currency: "INR",
      payment_method: "card",
      failure_reason: "bank_unavailable",
      detected_issue: "HDFC Bank 3DS OTP degradation",
      ai_recommendation: "payment_link",
      confidence: 0.89,
      recovery_probability: 0.82,
      expected_recovery: 10209,
      policy_decision: "APPROVED",
      status: "pending",
      created_at: "5m ago",
    },
    {
      transaction_id: "txn_35000_corp",
      customer_name: "Vikram Mehta",
      customer_email: "v.mehta@enterprises.com",
      amount: 35000,
      currency: "INR",
      payment_method: "netbanking",
      failure_reason: "gateway_timeout",
      detected_issue: "High-value checkout dropoff",
      ai_recommendation: "payment_link",
      confidence: 0.85,
      recovery_probability: 0.78,
      expected_recovery: 27300,
      policy_decision: "HUMAN_APPROVAL_REQUIRED",
      status: "failed",
      created_at: "12m ago",
    },
    {
      transaction_id: "txn_2999_sub",
      customer_name: "Rohan Gupta",
      customer_email: "rohan.g@startup.io",
      amount: 2999,
      currency: "INR",
      payment_method: "subscription",
      failure_reason: "card_expired",
      detected_issue: "Recurring mandate card expiry",
      ai_recommendation: "reminder",
      confidence: 0.94,
      recovery_probability: 0.91,
      expected_recovery: 2729.09,
      policy_decision: "APPROVED",
      status: "recovered",
      created_at: "25m ago",
    },
  ],
};

export const MOCK_TRANSACTIONS: TransactionListItem[] = [
  {
    id: "txn_4999_upi",
    customer_id: "cust_001",
    customer_name: "Aditya Verma",
    customer_email: "aditya.verma@example.com",
    amount: 4999,
    currency: "INR",
    payment_method: "upi",
    bank: "HDFC",
    status: "failed",
    failure_reason: "upi_timeout",
    attempt_number: 1,
    risk_score: 0.12,
    recovery_probability: 0.87,
    ai_recommendation: "payment_link",
    policy_decision: "APPROVED",
    created_at: "2026-08-29 14:12:05",
  },
  {
    id: "txn_12450_card",
    customer_id: "cust_002",
    customer_name: "Priya Sharma",
    customer_email: "priya.s@techcorp.in",
    amount: 12450,
    currency: "INR",
    payment_method: "card",
    bank: "ICICI",
    status: "pending",
    failure_reason: "bank_unavailable",
    attempt_number: 1,
    risk_score: 0.18,
    recovery_probability: 0.82,
    ai_recommendation: "payment_link",
    policy_decision: "APPROVED",
    created_at: "2026-08-29 14:05:10",
  },
  {
    id: "txn_35000_corp",
    customer_id: "cust_003",
    customer_name: "Vikram Mehta",
    customer_email: "v.mehta@enterprises.com",
    amount: 35000,
    currency: "INR",
    payment_method: "netbanking",
    bank: "SBI",
    status: "failed",
    failure_reason: "gateway_timeout",
    attempt_number: 1,
    risk_score: 0.22,
    recovery_probability: 0.78,
    ai_recommendation: "payment_link",
    policy_decision: "HUMAN_APPROVAL_REQUIRED",
    created_at: "2026-08-29 13:58:22",
  },
  {
    id: "txn_2999_sub",
    customer_id: "cust_004",
    customer_name: "Rohan Gupta",
    customer_email: "rohan.g@startup.io",
    amount: 2999,
    currency: "INR",
    payment_method: "subscription",
    bank: "AXIS",
    status: "recovered",
    failure_reason: "card_expired",
    attempt_number: 2,
    risk_score: 0.08,
    recovery_probability: 0.91,
    ai_recommendation: "reminder",
    policy_decision: "APPROVED",
    created_at: "2026-08-29 13:45:00",
  },
  {
    id: "txn_1850_upi",
    customer_id: "cust_005",
    customer_name: "Sneha Patel",
    customer_email: "sneha.p@designstudio.com",
    amount: 1850,
    currency: "INR",
    payment_method: "upi",
    bank: "KOTAK",
    status: "recovered",
    failure_reason: "upi_timeout",
    attempt_number: 1,
    risk_score: 0.09,
    recovery_probability: 0.94,
    ai_recommendation: "payment_link",
    policy_decision: "APPROVED",
    created_at: "2026-08-29 13:30:18",
  },
  {
    id: "txn_7499_card",
    customer_id: "cust_006",
    customer_name: "Arjun Nair",
    customer_email: "arjun.nair@fintech.co",
    amount: 7499,
    currency: "INR",
    payment_method: "card",
    bank: "HDFC",
    status: "failed",
    failure_reason: "insufficient_funds",
    attempt_number: 1,
    risk_score: 0.65,
    recovery_probability: 0.35,
    ai_recommendation: "reminder",
    policy_decision: "APPROVED",
    created_at: "2026-08-29 13:15:40",
  },
];

export const MOCK_PRIMARY_TRANSACTION: TransactionDetailResponse = {
  id: "txn_4999_upi",
  merchant_id: "mch_razorpay_demo",
  amount: 4999,
  currency: "INR",
  payment_method: "upi",
  payment_gateway: "razorpay",
  bank: "HDFC",
  status: "failed",
  failure_reason: "upi_timeout",
  attempt_number: 1,
  razorpay_payment_id: "pay_demo_upi_4999",
  razorpay_order_id: "order_demo_4999",
  created_at: "2026-08-29 14:12:05",
  updated_at: "2026-08-29 14:15:30",
  customer: {
    id: "cust_001",
    name: "Aditya Verma",
    email: "aditya.verma@example.com",
    phone: "+919876543210",
    total_transactions: 12,
    successful_transactions: 11,
    failed_transactions: 1,
    lifetime_value: 48200,
  },
  investigation: {
    root_cause: "Payment Method Degradation",
    confidence: 0.91,
    evidence: [
      "UPI failure rate increased 4.8x during attempt window in NPCI/HDFC link",
      "Customer historical success rate: 91.6% (11/12 successful payments)",
      "Zero fraud flags, trusted device & phone fingerprint verified",
      "Similar degradation incidents recovered successfully via Payment Link (92% conversion)",
    ],
    recovery_probability: 0.87,
    recommended_action: "Generate Payment Link",
    expected_recovery: 4349.13,
    policy_decision: "APPROVED",
    policy_checks: [
      { name: "Autonomous Amount Limit (<= ₹25,000)", status: "passed", detail: "Amount ₹4,999 is within autonomous approval limit" },
      { name: "Customer Fraud Risk (< 0.65)", status: "passed", detail: "Customer risk score 0.12 is safe" },
      { name: "Payment Link Policy", status: "passed", detail: "Payment link permitted for recoverable UPI degradation" },
      { name: "Max Retry Limit (<= 2 retries)", status: "passed", detail: "Attempt #1 is within retry limit" },
    ],
    rag_policy_reference: "Merchant Policy §2.1: Payment links allowed autonomously for technical degradation <= ₹25,000.",
  },
  recovery_actions: [
    {
      id: "act_101",
      action_type: "payment_link",
      reason: "Autonomous generation for UPI degradation",
      confidence: 0.91,
      policy_decision: "APPROVED",
      status: "pending",
      amount_recovered: 0,
      created_at: "2026-08-29 14:15:35",
    },
  ],
};

export const MOCK_RECOVERY_ACTIONS: RecoveryActionItem[] = [
  {
    id: "act_101",
    transaction_id: "txn_4999_upi",
    customer_name: "Aditya Verma",
    amount: 4999,
    currency: "INR",
    action_type: "payment_link",
    reason: "Autonomous payment link for UPI timeout",
    confidence: 0.91,
    policy_decision: "APPROVED",
    status: "pending",
    amount_recovered: 0,
    created_at: "2026-08-29 14:15:35",
  },
  {
    id: "act_102",
    transaction_id: "txn_35000_corp",
    customer_name: "Vikram Mehta",
    amount: 35000,
    currency: "INR",
    action_type: "payment_link",
    reason: "High-value checkout dropoff recovery",
    confidence: 0.85,
    policy_decision: "HUMAN_APPROVAL_REQUIRED",
    status: "pending",
    amount_recovered: 0,
    created_at: "2026-08-29 14:10:12",
  },
  {
    id: "act_103",
    transaction_id: "txn_2999_sub",
    customer_name: "Rohan Gupta",
    amount: 2999,
    currency: "INR",
    action_type: "reminder",
    reason: "Mandate card expiry update link",
    confidence: 0.94,
    policy_decision: "APPROVED",
    status: "recovered",
    amount_recovered: 2999,
    external_reference: "https://rzp.io/i/test_sub2999",
    created_at: "2026-08-29 13:45:05",
    completed_at: "2026-08-29 13:58:30",
  },
  {
    id: "act_104",
    transaction_id: "txn_1850_upi",
    customer_name: "Sneha Patel",
    amount: 1850,
    currency: "INR",
    action_type: "payment_link",
    reason: "UPI degradation recovery link",
    confidence: 0.94,
    policy_decision: "APPROVED",
    status: "recovered",
    amount_recovered: 1850,
    external_reference: "https://rzp.io/i/test_upi1850",
    created_at: "2026-08-29 13:30:20",
    completed_at: "2026-08-29 13:42:15",
  },
];

export const MOCK_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: "aud_101",
    transaction_id: "txn_4999_upi",
    agent_name: "PolicyGuardrailEngine",
    action: "evaluate_guardrails",
    reasoning_summary: "Autonomous payment link approved. Amount ₹4,999 <= ₹25k limit, customer risk score 0.12.",
    input_data: { amount: 4999, customer_id: "cust_aditya", failure_reason: "upi_timeout" },
    output_data: { verdict: "APPROVED", guardrails_passed: true },
    policy_result: "APPROVED",
    created_at: "2026-08-29 14:15:32",
  },
  {
    id: "aud_102",
    transaction_id: "txn_4999_upi",
    agent_name: "ActionExecutionAgent",
    action: "create_razorpay_payment_link",
    reasoning_summary: "Created Razorpay Test Mode Payment Link: https://rzp.io/i/test_4999upi",
    input_data: { amount: 4999, currency: "INR", customer: "Aditya Verma" },
    output_data: { id: "plink_test_8392183", short_url: "https://rzp.io/i/test_4999upi", status: "created" },
    policy_result: "APPROVED",
    created_at: "2026-08-29 14:15:35",
  },
  {
    id: "aud_103",
    transaction_id: "txn_35000_corp",
    agent_name: "PolicyGuardrailEngine",
    action: "evaluate_guardrails",
    reasoning_summary: "Transaction amount ₹35,000 > ₹25,000 threshold. Action routed for Human Review.",
    input_data: { amount: 35000, proposed_action: "payment_link" },
    output_data: { verdict: "HUMAN_APPROVAL_REQUIRED" },
    policy_result: "HUMAN_APPROVAL_REQUIRED",
    created_at: "2026-08-29 14:10:12",
  },
  {
    id: "aud_104",
    transaction_id: "txn_retry_card_99",
    agent_name: "PolicyGuardrailEngine",
    action: "evaluate_guardrails",
    reasoning_summary: "Automated retry blocked. Max retries (2) reached for transaction to protect gateway standing.",
    input_data: { attempt_number: 3, proposed_action: "retry" },
    output_data: { verdict: "BLOCKED" },
    policy_result: "BLOCKED",
    created_at: "2026-08-29 13:58:44",
  },
];

export const MOCK_AGENTS_OVERVIEW: AgentsOverviewResponse = {
  agents: [
    {
      name: "Revenue Detection Agent",
      role: "Detects failed payments, timeout blips, and checkout abandonment in real time",
      status: "active",
      total_runs: 10420,
      success_rate: 0.998,
      avg_latency_ms: 45,
      last_run_at: "Just now",
    },
    {
      name: "Root Cause Agent",
      role: "Correlates payment failure reasons with bank degradation anomalies & customer history",
      status: "active",
      total_runs: 4280,
      success_rate: 0.965,
      avg_latency_ms: 180,
      last_run_at: "1m ago",
    },
    {
      name: "RAG Policy Retriever",
      role: "Retrieves merchant recovery policies, retry caps, and incentive thresholds",
      status: "active",
      total_runs: 4280,
      success_rate: 0.992,
      avg_latency_ms: 65,
      last_run_at: "1m ago",
    },
    {
      name: "Policy & Guardrail Engine",
      role: "Deterministic evaluation engine preventing unauthorized financial actions",
      status: "active",
      total_runs: 4280,
      success_rate: 1.0,
      avg_latency_ms: 12,
      last_run_at: "1m ago",
    },
    {
      name: "Action Execution Agent",
      role: "Dispatches verified recovery actions to Razorpay Test Mode APIs",
      status: "active",
      total_runs: 1840,
      success_rate: 0.982,
      avg_latency_ms: 280,
      last_run_at: "2m ago",
    },
  ],
  recent_runs: [
    {
      id: "run_101",
      transaction_id: "txn_4999_upi",
      agent_name: "ActionExecutionAgent",
      status: "success",
      started_at: "2026-08-29 14:15:35",
      completed_at: "2026-08-29 14:15:36",
      latency_ms: 245,
      input_data: { action: "payment_link", amount: 4999 },
      output_data: { link_id: "plink_test_8392183", status: "created" },
    },
    {
      id: "run_102",
      transaction_id: "txn_4999_upi",
      agent_name: "PolicyGuardrailEngine",
      status: "success",
      started_at: "2026-08-29 14:15:32",
      completed_at: "2026-08-29 14:15:32",
      latency_ms: 15,
      input_data: { amount: 4999 },
      output_data: { verdict: "APPROVED" },
    },
    {
      id: "run_103",
      transaction_id: "txn_4999_upi",
      agent_name: "RootCauseAgent",
      status: "success",
      started_at: "2026-08-29 14:15:30",
      completed_at: "2026-08-29 14:15:31",
      latency_ms: 165,
      input_data: { failure_reason: "upi_timeout" },
      output_data: { root_cause: "Payment Method Degradation", confidence: 0.91 },
    },
  ],
};

export const MOCK_EVALUATION: EvaluationMetricsResponse = {
  total_transactions_analyzed: 10420,
  total_revenue_at_risk: 284210,
  total_revenue_recovered: 182450,
  overall_recovery_rate: 64.2,
  root_cause_accuracy: 0.924,
  strategy_recommendation_accuracy: 0.896,
  actions_approved_by_policy: 412,
  actions_blocked_by_guardrails: 34,
  actions_requiring_human_approval: 28,
  avg_agent_latency_ms: 185,
  category_breakdown: [
    { category: "UPI Gateway Timeout", total_failures: 184, predicted_correctly: 172, accuracy: 0.935, recovered_amount: 78200 },
    { category: "Checkout Session Abandonment", total_failures: 112, predicted_correctly: 98, accuracy: 0.875, recovered_amount: 42600 },
    { category: "Card 3DS / OTP Blip", total_failures: 96, predicted_correctly: 89, accuracy: 0.927, recovered_amount: 38900 },
    { category: "Subscription Mandate Expired", total_failures: 82, predicted_correctly: 78, accuracy: 0.951, recovered_amount: 22750 },
  ],
  ml_roc_auc_score: 0.912,
  ml_precision: 0.894,
  ml_recall: 0.868,
  ml_f1_score: 0.881,
};
